info:
  app:
    name: hello-actuator
    company: hhj

management:
  # Info
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
  
  # End Point
  endpoint:
    health:
      show-components: always

  # End Points
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
